filter:
  excluded_paths:
    - test/*
build:
  tests:
    before:
      - unzip -x "test/var/lib/20200101 Groupertabellen v20190919.zip" -d test/var/lib/
      - kerapu kerapu:shredder "test/var/lib/20200101 BoomBestanden v20190919.xml"  test/var/lib/
      - kerapu kerapu:shredder "test/var/lib/20200101 Referenties v20190919.xml" test/var/lib/

    override:
      - command: coverage run -m unittest discover -s test -p *Test.py
        coverage:
          file: '.coverage'
          config_file: '.coveragerc'
          format: 'py-cc'

  nodes:
    analysis:
      tests:
        override:
          - py-scrutinizer-run

