filter:
    excluded_paths:
        - test/*

before_commands:
  - sudo pip3 install cleo==0.6.1
  - sudo pip3 install lxml
  - sudo pip3 install coverage

build:
    dependencies:
        before:
        - pip3 install cleo==0.6.1
        - pip3 install lxml
        - pip3 install coverage

    tests:
        before:
          - unzip -x test/var/lib/20170101\ Grouper\ Tabellen\ v20161117.zip -d test/var/lib/
          - kerapu kerapu:shredder test/var/lib/20170101\ BoomBestanden\ v20161117.xml  test/var/lib/
          - kerapu kerapu:shredder test/var/lib/20170101\ Referenties\ v20161117.xml test/var/lib/

        override:
            -
                command: coverage run -m unittest discover -s test -p *Test.py
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'

